// Generates src/design/tokens.css (Tailwind @theme) from shared/design/tokens.json.
import { readFileSync, writeFileSync } from 'node:fs'

const tokens = JSON.parse(readFileSync(new URL('../../../shared/design/tokens.json', import.meta.url)))
const kebab = (s) => s.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`)
const lines = []
const add = (name, value) => lines.push(`  --${name}: ${value};`)

for (const [k, v] of Object.entries(tokens.color.identity)) add(`color-${kebab(k)}`, v)
for (const [k, v] of Object.entries(tokens.color.theme.estudio)) add(`color-${kebab(k)}`, v)
for (const [k, v] of Object.entries(tokens.color.sprite)) add(`color-sprite-${kebab(k)}`, v)
for (const [k, v] of Object.entries(tokens.color.state)) add(`color-estado-${kebab(k)}`, v)
for (const p of tokens.players) add(`color-jogador-${p.slot}`, p.color)
add('font-display', tokens.font.display)
add('font-sans', tokens.font.body)
add('font-label', tokens.font.label)
for (const [k, v] of Object.entries(tokens.radius)) add(`radius-${k}`, `${v}px`)
for (const [k, v] of Object.entries(tokens.motion)) {
  add(`ease-${k}`, v.easing)
}

const cartao = Object.entries(tokens.color.theme.cartao)
  .map(([k, v]) => `  --color-${kebab(k)}: ${v};`)
  .join('\n')

writeFileSync(
  new URL('../src/design/tokens.css', import.meta.url),
  `/* GENERATED by scripts/gen-tokens.mjs from shared/design/tokens.json. Do not edit. */\n` +
    // `static`: emit every token even if no utility uses it (components read them via var()).
    `@theme static {\n${lines.join('\n')}\n}\n\n[data-theme='cartao'] {\n${cartao}\n}\n`,
)
console.log('wrote src/design/tokens.css')
