import { Assets, type Texture } from 'pixi.js'
import { z } from 'zod'

const uiManifestSchema = z.record(z.string(), z.string())

let manifest: Promise<Record<string, string>> | undefined

/** `assets/ui/ui.json`: sprite name → path (generated by scripts/assets/build_ui.py). */
export function uiManifest(): Promise<Record<string, string>> {
  manifest ??= fetch('/ui/ui.json')
    .then((r) => r.json())
    .then((json) => uiManifestSchema.parse(json))
  return manifest
}

export async function uiUrl(name: string): Promise<string> {
  const path = (await uiManifest())[name]
  if (!path) throw new Error(`Unknown UI sprite: ${name}`)
  return `/${path}`
}

export async function loadUiTextures<K extends string>(names: readonly K[]): Promise<Record<K, Texture>> {
  const entries = await Promise.all(
    names.map(async (name) => [name, await Assets.load<Texture>(await uiUrl(name))] as const),
  )
  return Object.fromEntries(entries) as Record<K, Texture>
}
